import type { Metadata, Viewport } from "next";

import clsx from "clsx";

import { HeroProviders } from "@/providers/hero-ui-provider";
import { geistMono, geistSans, lexend } from "@/constant/fonts";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: {
    default: "Next.js Boilerplate",
    template: `%s - Next.js Boilerplate`,
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      className={`${geistMono.variable} ${geistSans.variable} ${lexend.variable}`}
      lang="en"
    >
      <body
        className={clsx("min-h-screen bg-background font-sans antialiased")}
      >
        <HeroProviders>{children}</HeroProviders>
      </body>
    </html>
  );
}
